name: Distribute mobile to firebase

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'Manual Debug Build'
        description: 'Release Notes'

jobs:
  build:
    name: Building and distributing app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: build release
        run: ./gradlew assembleRelease

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: upload artifact to Firebase App Distribution
        run: |
          bundle install
          bundle exec fastlane deployAndroidToFirebase
