name: PR Checks

on:
  pull_request:
    types: [ labeled, unlabeled, reopened, synchronize ]
    branches:
      - main
      - 'release*'
      - develop
  workflow_dispatch:

# Cancel previous jobs within the same workflow and branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static_analysis:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare environment
        run: |
          export GRADLE_USER_HOME=`pwd`/.gradle
          chmod +x ./gradlew
      - name: Static Analysis
        run: |
          bundle install
          ./gradlew ktlint
          ./gradlew detekt

  build_android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare environment
        run: |
          export GRADLE_USER_HOME=`pwd`/.gradle
          chmod +x ./gradlew
      - name: Assemble
        run: |
          ./gradlew :composeApp:assemble --stacktrace

  unit_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare environment
        run: |
          export GRADLE_USER_HOME=`pwd`/.gradle
          chmod +x ./gradlew
      - name: Unit tests
        run: |
          ./gradlew test --stacktrace
